name: Build and Deploy glnk-dev Webapp to GitHub Pages
description: Build and Deploy glnk-dev Webapp to GitHub Pages
branding:
  icon: book-open
  color: yellow

inputs:
  GLNK_USERNAME:
    description: "glnk.dev username"
    required: true
  GLNK_URLMAP_PATH:
    description: "glnk.dev URL map path"
    required: false
    default: glnk.yaml
  GLNK_PUBLIC_URL:
    description: "glnk.dev public URL"
    required: false
    default: ""
  GLNK_PATH_SEGMENTS:
    description: "glnk.dev path segment count"
    required: false
    default: "0"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: glnk-dev/webapp

    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: main
        sparse-checkout: |
          ${{ inputs.GLNK_URLMAP_PATH }}

    - run: |
        echo REACT_APP_GLNK_USERNAME=${{ inputs.GLNK_USERNAME }} > .env

    - name: Prebuild index.html
      uses: cuchi/jinja2-action@v1.2.2
      with:
        template: public/index.html.j2
        output_file: public/index.html
      env:
        GLNK_USERNAME: ${{ inputs.GLNK_USERNAME }}

    - name: Prebuild 404.html
      uses: cuchi/jinja2-action@v1.2.2
      with:
        template: public/404.html.j2
        output_file: public/404.html
      env:
        GLNK_PATH_SEGMENTS: ${{ inputs.GLNK_PATH_SEGMENTS }}

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x

    - name: Cache NPM packages
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install NPM packages
      shell: bash
      run: npm install

    - name: Build project
      shell: bash
      run: npm run build
      env:
        PUBLIC_URL: ${{ inputs.GLNK_PUBLIC_URL }}

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: build

    - name: Deploy to GitHub pages
      id: deployment
      uses: actions/deploy-pages@v4
