name: Build and Deploy glnk-dev Webapp to GitHub Pages
description: Build and Deploy glnk-dev Webapp to GitHub Pages
branding:
  icon: book-open
  color: yellow

inputs:
  GLNK_USERNAME:
    description: "glnk.dev username"
    required: true
  GLNK_AUTHORIZED_ONLY:
    description: "glnk.dev authorized only"
    required: false
    default: 0
  GLNK_URLMAP_PATH:
    description: "glnk.dev URL map path"
    required: false
    default: glnk.yaml
  GLNK_PUBLIC_URL:
    description: "glnk.dev public URL"
    required: false
    default: ""
  GLNK_PATH_SEGMENTS:
    description: "glnk.dev path segment count"
    required: false
    default: "0"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: glnk-dev/webapp

    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: main
        sparse-checkout: |
          ${{ inputs.GLNK_URLMAP_PATH }}

    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v3
      with:
        workload_identity_provider: projects/1042177442694/locations/global/workloadIdentityPools/github/providers/glnk-dev
        service_account: glnk-dev@playground-365100.iam.gserviceaccount.com

    - id: secrets
      name: Get secrets from Google Secret Manager
      uses: google-github-actions/get-secretmanager-secrets@v3
      with:
        secrets: |-
          firebase_api_key:playground-365100/glnk-dev-firebase-api-key
          firebase_app_id:playground-365100/glnk-dev-firebase-app-id

    - name: Replace template variables
      shell: bash
      run: |
        mv main/${{ inputs.GLNK_URLMAP_PATH }} public/glnk.yaml
        echo REACT_APP_GLNK_USERNAME=$GLNK_USERNAME > .env
        echo REACT_APP_GLNK_AUTHORIZED_ONLY=$GLNK_AUTHORIZED_ONLY >> .env
        echo REACT_APP_FIREBASE_API_KEY=$FIREBASE_API_KEY >> .env
        echo REACT_APP_FIREBASE_APP_ID=$FIREBASE_APP_ID >> .env
        find ./public -type f -name "*.html" -exec sed -i "s/GLNK_USERNAME/$GLNK_USERNAME/g; s/GLNK_PATH_SEGMENTS/$GLNK_PATH_SEGMENTS/g" {} +
      env:
        GLNK_USERNAME: ${{ inputs.GLNK_USERNAME }}
        GLNK_AUTHORIZED_ONLY: ${{ inputs.GLNK_AUTHORIZED_ONLY }}
        FIREBASE_API_KEY: ${{ steps.secrets.outputs.firebase_api_key }}
        FIREBASE_APP_ID: ${{ steps.secrets.outputs.firebase_app_id }}
        GLNK_PATH_SEGMENTS: ${{ inputs.GLNK_PATH_SEGMENTS }}

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x

    - name: Cache NPM packages
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install NPM packages
      shell: bash
      run: npm install

    - name: Build project
      shell: bash
      run: npm run build
      env:
        PUBLIC_URL: ${{ inputs.GLNK_PUBLIC_URL }}

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: build

    - name: Deploy to GitHub pages
      id: deployment
      uses: actions/deploy-pages@v4
