name: Build and Deploy glnk-dev Webapp to GitHub Pages
description: Build and Deploy glnk-dev Webapp to GitHub Pages
branding:
  icon: book-open
  color: yellow

inputs:
  GLNK_USERNAME:
    description: "Your GitHub username (used as subdomain: username.glnk.dev). Not required for homepage mode."
    required: false
    default: ""
  GLNK_ACCESS_MODE:
    description: "Site mode: 'static' = read-only, 'public' = login to edit, 'private' = login required, 'homepage' = glnk.dev signup page"
    required: false
    default: "static"
  GLNK_PUBLIC_URL:
    description: "Custom domain URL (leave empty for default username.glnk.dev)"
    required: false
    default: ""
  GLNK_PATH_SEGMENTS:
    description: "Number of path segments to preserve for SPA routing (0 for root domain)"
    required: false
    default: "0"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v6
      with:
        repository: glnk-dev/webapp

    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v3
      with:
        project_id: glnk-dev
        workload_identity_provider: projects/761634418776/locations/global/workloadIdentityPools/github/providers/glnk-dev

    - id: secrets
      name: Get secrets from Google Secret Manager
      uses: google-github-actions/get-secretmanager-secrets@v3
      with:
        secrets: |-
          gh_app_id:glnk-dev/gh-app-glnk-manager-id
          gh_app_private_key:glnk-dev/gh-app-glnk-manager-private-key
          firebase_api_key:glnk-dev/glnk-dev-firebase-api-key
          firebase_app_id:glnk-dev/glnk-dev-firebase-app-id

    - uses: actions/create-github-app-token@v2
      if: inputs.GLNK_ACCESS_MODE != 'homepage'
      id: app-token
      with:
        app-id: ${{ steps.secrets.outputs.gh_app_id }}
        private-key: ${{ steps.secrets.outputs.gh_app_private_key }}
        owner: ${{ github.repository_owner }}
        repositories: community

    - name: Checkout urlmap
      if: inputs.GLNK_ACCESS_MODE != 'homepage'
      uses: actions/checkout@v6
      with:
        repository: glnk-dev/community
        token: ${{ steps.app-token.outputs.token }}
        path: community
        sparse-checkout: |
          users/glnk-${{ inputs.GLNK_USERNAME }}.yaml

    - name: Setup user site
      if: inputs.GLNK_ACCESS_MODE != 'homepage'
      shell: bash
      run: |
        mv community/users/glnk-$GLNK_USERNAME.yaml public/glnk.yaml || true
        find ./public -type f -name "*.html" -exec sed -i "s/GLNK_USERNAME/$GLNK_USERNAME/g; s/GLNK_PATH_SEGMENTS/$GLNK_PATH_SEGMENTS/g; s|PUBLIC_URL|$PUBLIC_URL|g" {} +
      env:
        GLNK_USERNAME: ${{ inputs.GLNK_USERNAME }}
        GLNK_PATH_SEGMENTS: ${{ inputs.GLNK_PATH_SEGMENTS }}
        PUBLIC_URL: ${{ inputs.GLNK_PUBLIC_URL }}

    - name: Setup homepage
      if: inputs.GLNK_ACCESS_MODE == 'homepage'
      shell: bash
      run: |
        find ./public -type f -name "*.html" -exec sed -i "s/GLNK_USERNAME\.//g; s/GLNK_PATH_SEGMENTS/0/g; s|PUBLIC_URL|$PUBLIC_URL|g" {} +
      env:
        PUBLIC_URL: ${{ inputs.GLNK_PUBLIC_URL }}

    - name: Create .env file
      shell: bash
      run: |
        echo REACT_APP_GLNK_USERNAME=$GLNK_USERNAME > .env
        echo REACT_APP_GLNK_ACCESS_MODE=$GLNK_ACCESS_MODE >> .env
        echo REACT_APP_FIREBASE_API_KEY=$FIREBASE_API_KEY >> .env
        echo REACT_APP_FIREBASE_APP_ID=$FIREBASE_APP_ID >> .env
      env:
        GLNK_USERNAME: ${{ inputs.GLNK_USERNAME }}
        GLNK_ACCESS_MODE: ${{ inputs.GLNK_ACCESS_MODE }}
        FIREBASE_API_KEY: ${{ steps.secrets.outputs.firebase_api_key }}
        FIREBASE_APP_ID: ${{ steps.secrets.outputs.firebase_app_id }}

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x

    - name: Cache NPM packages
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install NPM packages
      shell: bash
      run: npm install

    - name: Build project
      shell: bash
      run: npm run build
      env:
        PUBLIC_URL: ${{ inputs.GLNK_PUBLIC_URL }}

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: build

    - name: Deploy to GitHub pages
      id: deployment
      uses: actions/deploy-pages@v4
